version: "3.7"
services:
  db:
    build: mysql
    image: campaign_db
    container_name: campaign_db
    ports:
      - 3306:3306
  app:
    build: rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: campaign_app
    container_name: campaign_app
    environment:
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 3000:3000
    volumes:
      - ./rails:/campaignApp
    depends_on:
      - db